set(CMAKE_SYSTEM_NAME Linux)

include(CMakeForceCompiler)

CMAKE_FORCE_C_COMPILER(mpifcc GNU)
CMAKE_FORCE_CXX_COMPILER(mpiFCC GNU)
if (with_example)
  CMAKE_FORCE_Fortran_COMPILER(mpifrt GNU)
endif()

set(CMAKE_FIND_ROOT_PATH /opt/FJSVpclang/1.2.0)   # RIIT CX400
set(CMAKE_INCLUDE_PATH /opt/FJSVpclang/1.2.0/include)
set(CMAKE_LIBRARY_PATH /opt/FJSVpclang/1.2.0/lib64)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(TARGET_ARCH "INTEL_F_TCS")
set(USE_F_TCS "YES")
